#pragma once
#define HUANFACE_VERSION_MAJOR 0
#define HUANFACE_VERSION_MINOR 2
#define HUANFACE_VERSION_PATCH 0
#define HUANFACE_VERSION_STRING "0.2.0-phase2"
#define HUANFACE_BUNDLE_FORMAT "HuanFaceBundle"
#define HUANFACE_BUNDLE_VERSION "1.0"
