#include "face/MediaPipePixelSource.h"

#include <algorithm>
#include <chrono>
#include <cstring>

#include "core/logging/Logger.h"
#include "graphics/D3D11/D3D11Shader.h"
#include "graphics/D3D11/D3D11Texture.h"

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <wrl/client.h>

// Embedded shaders (generated by cmake/EmbedShader.cmake).
#include <fullscreen_vs.hlsl.h>
#include <tracker_ps.hlsl.h>

namespace haocam {

using Microsoft::WRL::ComPtr;

namespace {
constexpr const char* kCategory = "tracking";
} // namespace

// .cpp-local pipeline holder (keeps D3D11 types out of the header).
struct DownscalePipeline {
    gfx::D3D11ShaderProgram program;
    gfx::D3D11SamplerCache samplers;
    ComPtr<ID3D11Texture2D> target;
    ComPtr<ID3D11Texture2D> staging;
    gfx::D3D11TextureViews views{};
};

std::unique_ptr<D3D11PixelSource> D3D11PixelSource::create(void* d3d11Device,
                                                           void* d3d11Context) {
    if (!d3d11Device || !d3d11Context) return nullptr;
    auto* source = new D3D11PixelSource();
    source->m_device = static_cast<ID3D11Device*>(d3d11Device);
    source->m_context = static_cast<ID3D11DeviceContext*>(d3d11Context);
    auto* pipeline = new DownscalePipeline();
    if (!pipeline->program.loadFromEmbeddedSource(
            source->m_device, shaders::k_fullscreen_vs_hlsl,
            shaders::k_fullscreen_vs_hlsl_size, shaders::k_tracker_ps_hlsl,
            shaders::k_tracker_ps_hlsl_size)) {
        HAOCAM_LOG_ERROR(kCategory, "Tracking downscale shader failed to compile");
        delete pipeline;
        delete source;
        return nullptr;
    }
    source->m_downscalePipeline = pipeline;
    return std::unique_ptr<D3D11PixelSource>(source);
}

D3D11PixelSource::~D3D11PixelSource() {
    auto* pipeline = static_cast<DownscalePipeline*>(m_downscalePipeline);
    if (pipeline) delete pipeline;
}

bool D3D11PixelSource::readRGBA(const TrackingInput& input, std::vector<uint8_t>& dst,
                                uint32_t& width, uint32_t& height) {
    if (!input.gpu || !input.gpu->native() || !m_downscalePipeline) return false;
    auto* pipeline = static_cast<DownscalePipeline*>(m_downscalePipeline);
    auto* views = static_cast<gfx::D3D11TextureViews*>(input.gpu->userData());
    if (!views || !views->srvPlane0) return false;

    const uint32_t srcWidth = input.gpu->width();
    const uint32_t srcHeight = input.gpu->height();
    if (srcWidth == 0 || srcHeight == 0) return false;

    // Working resolution (aspect preserved, capped width).
    if (m_trackWidth == 0 || input.width != srcWidth) {
        m_trackWidth = std::min(m_maxWorkingWidth, srcWidth);
        m_trackHeight = std::max(16u, srcHeight * m_trackWidth / srcWidth);

        D3D11_TEXTURE2D_DESC desc{};
        desc.Width = m_trackWidth;
        desc.Height = m_trackHeight;
        desc.MipLevels = 1;
        desc.ArraySize = 1;
        desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        desc.SampleDesc.Count = 1;
        desc.Usage = D3D11_USAGE_DEFAULT;
        desc.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
        if (pipeline->target) pipeline->target.Reset();
        if (FAILED(m_device->CreateTexture2D(&desc, nullptr,
                                             pipeline->target.GetAddressOf()))) {
            HAOCAM_LOG_ERROR(kCategory, "Tracking target creation failed");
            return false;
        }
        D3D11_TEXTURE2D_DESC stagingDesc = desc;
        stagingDesc.Usage = D3D11_USAGE_STAGING;
        stagingDesc.BindFlags = 0;
        stagingDesc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
        if (pipeline->staging) pipeline->staging.Reset();
        if (FAILED(m_device->CreateTexture2D(&stagingDesc,
                                             nullptr, pipeline->staging.GetAddressOf()))) {
            HAOCAM_LOG_ERROR(kCategory, "Tracking staging creation failed");
            return false;
        }
        if (pipeline->views.rtv) {
            pipeline->views.rtv->Release();
            pipeline->views.rtv = nullptr;
        }
        if (pipeline->views.srvPlane0) {
            pipeline->views.srvPlane0->Release();
            pipeline->views.srvPlane0 = nullptr;
        }
        if (FAILED(m_device->CreateRenderTargetView(pipeline->target.Get(), nullptr,
                                                    &pipeline->views.rtv)) ||
            FAILED(m_device->CreateShaderResourceView(pipeline->target.Get(), nullptr,
                                                      &pipeline->views.srvPlane0))) {
            HAOCAM_LOG_ERROR(kCategory, "Tracking target views creation failed");
            return false;
        }
    }

    const auto start = std::chrono::steady_clock::now();

    // Downscale draw (BGRA8 target holding SRGBA byte order).
    ID3D11RenderTargetView* rtv = pipeline->views.rtv;
    m_context->OMSetRenderTargets(1, &rtv, nullptr);
    D3D11_VIEWPORT viewport{0, 0, static_cast<float>(m_trackWidth),
                            static_cast<float>(m_trackHeight), 0.0f, 1.0f};
    m_context->RSSetViewports(1, &viewport);
    ID3D11ShaderResourceView* srv = views->srvPlane0;
    m_context->PSSetShaderResources(0, 1, &srv);
    ID3D11SamplerState* sampler = pipeline->samplers.linearClamp(m_device);
    m_context->PSSetSamplers(0, 1, &sampler);
    m_context->VSSetShader(pipeline->program.vertexShader(), nullptr, 0);
    m_context->PSSetShader(pipeline->program.pixelShader(), nullptr, 0);
    m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    m_context->Draw(3, 0);

    // Readback into the reusable CPU buffer.
    m_context->CopyResource(pipeline->staging.Get(), pipeline->target.Get());
    D3D11_MAPPED_SUBRESOURCE mapped{};
    if (FAILED(m_context->Map(pipeline->staging.Get(), 0, D3D11_MAP_READ, 0, &mapped))) {
        return false;
    }
    dst.resize(static_cast<size_t>(m_trackWidth) * m_trackHeight * 4);
    const size_t rowBytes = static_cast<size_t>(m_trackWidth) * 4;
    if (mapped.RowPitch == rowBytes) {
        std::memcpy(dst.data(), mapped.pData, dst.size());
    } else {
        const uint8_t* src = static_cast<const uint8_t*>(mapped.pData);
        for (uint32_t row = 0; row < m_trackHeight; ++row) {
            std::memcpy(dst.data() + row * rowBytes, src + row * mapped.RowPitch,
                        rowBytes);
        }
    }
    m_context->Unmap(pipeline->staging.Get(), 0);

    m_lastReadMs =
        std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start)
            .count();
    width = m_trackWidth;
    height = m_trackHeight;
    return true;
}

} // namespace haocam
