# Writes haocam_build_rev.h containing the current git short revision.
# Runs on every build (add_custom_target ALL); the file is only rewritten
# when its content changes, so this does not trigger perpetual relinks.
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE HAOCAM_REV
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE HAOCAM_GIT_RESULT)
if(NOT HAOCAM_GIT_RESULT EQUAL 0 OR HAOCAM_REV STREQUAL "")
    set(HAOCAM_REV "unknown")
endif()
set(content "// Generated by cmake/WriteBuildRev.cmake - do not edit.\n"
            "#define HAOCAM_BUILD_REV \"${HAOCAM_REV}\"\n")
set(old "")
if(EXISTS "${REV_OUT}")
    file(READ "${REV_OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${REV_OUT}" ${content})
    message(STATUS "haocam build stamp -> ${HAOCAM_REV}")
endif()
